"""Recreate migrations

Revision ID: 1a8f78bb7e3c
Revises: 
Create Date: 2024-09-20 17:26:12.758454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a8f78bb7e3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uname', sa.String(length=100), nullable=False),
    sa.Column('udob', sa.Date(), nullable=False),
    sa.Column('uemail', sa.String(length=100), nullable=False),
    sa.Column('uphone', sa.String(length=15), nullable=False),
    sa.Column('upassword', sa.String(length=100), nullable=False),
    sa.Column('ugender', sa.String(length=10), nullable=False),
    sa.Column('ustate', sa.String(length=50), nullable=False),
    sa.Column('ucity', sa.String(length=50), nullable=False),
    sa.Column('urole', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('uemail')
    )
    op.create_table('qualification',
    sa.Column('qid', sa.Integer(), nullable=False),
    sa.Column('qualification_type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('qid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qualification')
    op.drop_table('user')
    # ### end Alembic commands ###
