"""empty message

Revision ID: 4ec5c4dc3ddb
Revises: 10ea922f274c
Create Date: 2024-09-20 01:56:09.324612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ec5c4dc3ddb'
down_revision = '2e8eaf23f7dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('cid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cname', sa.String(), nullable=False),
    sa.Column('cdescription', sa.String(), nullable=False),
    sa.Column('cduration', sa.String(), nullable=False),
    sa.Column('cfees', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('cid')
    )
    op.create_table('enquiry_status',
    sa.Column('statusid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('statusname', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('statusid')
    )
    op.create_table('user',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uname', sa.String(length=100), nullable=False),
    sa.Column('udob', sa.Date(), nullable=False),
    sa.Column('uemail', sa.String(length=100), nullable=False),
    sa.Column('uphone', sa.String(length=15), nullable=False),
    sa.Column('upassword', sa.String(length=100), nullable=False),
    sa.Column('ugender', sa.String(length=10), nullable=False),
    sa.Column('ustate', sa.String(length=50), nullable=False),
    sa.Column('ucity', sa.String(length=50), nullable=False),
    sa.Column('urole', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('uemail')
    )
    op.create_table('enquiry',
    sa.Column('eid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('ehighestqualification', sa.String(), nullable=False),
    sa.Column('emarks', sa.Float(), nullable=False),
    sa.Column('egraduateyear', sa.Integer(), nullable=False),
    sa.Column('esource', sa.String(), nullable=False),
    sa.Column('edate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.cid'], ),
    sa.ForeignKeyConstraint(['status_id'], ['enquiry_status.statusid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('eid')
    )
    op.create_table('qualification',
    sa.Column('qid', sa.Integer(), nullable=False),
    sa.Column('qualification_type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('qid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qualification')
    op.drop_table('enquiry')
    op.drop_table('user')
    op.drop_table('enquiry_status')
    op.drop_table('course')
    # ### end Alembic commands ###
