"""empty message

Revision ID: 9d3bd0aa1eb1
Revises: 4ec5c4dc3ddb
Create Date: 2024-09-20 01:58:41.355011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d3bd0aa1eb1'
down_revision = '4ec5c4dc3ddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qualification',
    sa.Column('qid', sa.Integer(), nullable=False),
    sa.Column('qualification_type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('qid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qualification')
    # ### end Alembic commands ###
