"""empty message

Revision ID: b241d77d7112
Revises: c5131b993513
Create Date: 2024-09-20 17:24:54.421977

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'b241d77d7112'
down_revision = 'c5131b993513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disable', sa.Boolean(), nullable=True))
        batch_op.drop_column('disabled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disabled', mssql.BIT(), autoincrement=False, nullable=True))
        batch_op.drop_column('disable')

    # ### end Alembic commands ###
