"""empty message

Revision ID: f9422e8a6463
Revises: b241d77d7112
Create Date: 2024-09-20 18:07:25.923851

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'f9422e8a6463'
down_revision = 'b241d77d7112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('disable')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disable', mssql.BIT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
